\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\PassOptionsToPackage{usenames,dvipsnames}{color} % color is loaded by hyperref
\hypersetup{unicode=true,
            pdftitle={LiMo WiSe 16/17 Sheet 5: Ex 1},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{{#1}}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\ImportTok}[1]{{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{{#1}}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{{#1}}}}
\newcommand{\BuiltInTok}[1]{{#1}}
\newcommand{\ExtensionTok}[1]{{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{{#1}}}
\newcommand{\RegionMarkerTok}[1]{{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{{#1}}}}
\newcommand{\NormalTok}[1]{{#1}}
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}
  \title{LiMo WiSe 16/17 Sheet 5: Ex 1}
  \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \author{}
  \preauthor{}\postauthor{}
  \date{}
  \predate{}\postdate{}


% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi


\begin{document}
\maketitle

\section{Task:}\label{task}

We have obtained the following matrices as a result of a regression
analysis (with intercept \(\beta_0\)).

\[
\begin{aligned}
X'X &= 
\begin{pmatrix}
9   & 136  & 269  & 260  \\
136 & 2114 & 4176 & 3583\\
269 & 4176 & 8257 & 7104\\
260 & 3583 & 7104 & 12276\\
\end{pmatrix} \\
X'y &=
\begin{pmatrix}
45 \\
648 \\
1283 \\
1821 \\
\end{pmatrix} \\
(X'X)^{-1} &= 
\begin{pmatrix}
9.610932  & 0.0085878  & -0.2791475  & -0.0445217\\
0.0085878 & 0.5099641  & -0.2588636  & 0.0007765\\
-0.2791475 & -0.2588636 &  0.1395     & 0.0007369\\
-0.0445217 & 0.0007765  &  0.0007396  & 0.0003698\\
\end{pmatrix}\\
(X'X)^{-1}X'y &=
\begin{pmatrix}
-1.163461\\
0.135270\\
0.019950\\
0.121954\\
\end{pmatrix}\\
y'y &= 285
\end{aligned}
\]

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\item
  Calculate the test statistic for the test of overall regression and
  illustrate your intermediate steps in an ANOVA table. Interpret the
  result.
\item
  Calculate \(\hat{\beta}\) and the diagonal elements of
  \(\widehat{Cov}(\hat{\beta})\) and test the hypothesis whether each
  regression coefficient equals 0.
\item
  Define the matrix \(C\) for testing the hypothesis
  \(H_0 : \beta_0 = 0, \beta_1 = \beta_3, \beta_2 = 0\).
\item
  Find the model equation for the reduced model in c).
\end{enumerate}

\section{Answers}\label{answers}

\subsection{a)}\label{a}

ANOVA-Table:

\begin{longtable}[c]{@{}lllll@{}}
\toprule
Source & DF & Sum of squares & Mean squares & F\tabularnewline
\midrule
\endhead
Model & 3 & 57.97 & 19.32 & 47.7\tabularnewline
Error & 5 & 203 & 0.405 &\tabularnewline
Total & 8 & 60 & &\tabularnewline
\bottomrule
\end{longtable}

\subsubsection{Obtaining degrees of freedom
(DF)}\label{obtaining-degrees-of-freedom-df}

\begin{itemize}
\tightlist
\item
  \(DF_{\text{model}} = p\) and we can get \(p+1\) from the dimension of
  \(X'X \Rightarrow 4 \Rightarrow p = 3\).
\item
  \(DF_{\text{total}} = n - 1\); \(n = (X'X)_{11} = 9\).
\item
  \(DF_{\text{error}} = n - p - 1 = 5\).
\end{itemize}

\subsubsection{Obtaining Sum of Squares}\label{obtaining-sum-of-squares}

\paragraph{Total Sum of Squares}\label{total-sum-of-squares}

\[
\begin{aligned}
SST &= \sum_{i = 1}^n y_i^2 - n\bar{y}^2\\
 &= y'y - n\left( \frac{(X'y)_{11}}{n} \right)^2\\
 &= 285 - 9\left( \frac{45}{9} \right)^2\\
 &= 60
\end{aligned}
\]

\paragraph{Residual Sum of Squares}\label{residual-sum-of-squares}

\[
\begin{aligned}
SSR &= \sum_{i = 1}^n \hat{y}_i^2 - n\bar{y}^2\\
&= \hat{y}'\hat{y} - n\bar{y}^2\\
&\Rightarrow \text{Using $\hat{y} = X(X'X)^{-1}X'y$} \\
&=(X(X'X)^{-1}X'y)'X(X'X)^{-1}X'y - n\bar{y}^2\\
&=y'X(X'X)^{-1}X'X(X'X)^{-1}X'y - n\bar{y}^2\\
&=y'X(X'X)^{-1}X'y - n\bar{y}^2\\
&=(X'y)'X(X'X)^{-1}X'y - n\bar{y}^2\\
&=
\begin{pmatrix} 45 & 648 & 1283 & 1821 \end{pmatrix}
\begin{pmatrix} -1.16 \\  0.4 \\  0.02 \\  0.12  \end{pmatrix}  - n\bar{y}^2 \\
&= 57.97
\end{aligned}
\]

\paragraph{Error Sum of Squares}\label{error-sum-of-squares}

\[
SSE = SST - SSR = 60 - 57.93 = 2.03
\]

\subsubsection{Mean Squres}\label{mean-squres}

\begin{itemize}
\tightlist
\item
  Residual mean square \(MSR = \frac{SSR}{p} = 19.32\)
\item
  Error mean square \(MSE = \frac{SSE}{n-p-1} = 0.405\)
\end{itemize}

\subsubsection{F-value}\label{f-value}

\[
F = \frac{MSR}{MSE} = 47.7 \overset{H_0}{\sim}F(3,5)
\]

To obtain the (two-sided) p-value:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(}\DecValTok{1} \NormalTok{-}\StringTok{ }\KeywordTok{pt}\NormalTok{(}\DecValTok{47}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{5}\NormalTok{)) *}\StringTok{ }\DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.003679194
\end{verbatim}

We reject \(H_0: \beta_1 = \beta_2 = \beta_3 = 0\) because \(p < 0.05\).

\subsection{b)}\label{b}

\[
\hat{\beta} = (X'X)^{-1}X'y =
\begin{pmatrix}
-1.163461\\
0.135270\\
0.019950\\
0.121954\\
\end{pmatrix}\\
\]

\[
\widehat{Cov}(\hat{\beta}) = \hat{\sigma}^2(X'X)^{-1}
\]

with

\[
\hat{\sigma}^2 = \frac{\sum_{i = 1}^n \hat{\epsilon_i}^2}{n - p - 1} = MSE = 0.405
\]

We need the diagonal elements of
\(diag(\widehat{Cov}(\hat{\beta})) = (3.8924, 0.2065, 0.0565, 0.00015)\).

Testing wether each regression coefficient equals 0:

\[
T = \frac{\hat{\beta}_k - \beta_k}{\hat{\sigma}_k} \sim t(n - p - 1, 0)
\]

In our case: \(H_0:\beta_k = 0\) hence

\[T = \frac{\hat{\beta}_k}{\hat{\sigma}_{\beta_k}}\]

with

\[
\hat{\sigma}_{\beta_k} = \sqrt{\widehat{Cov}(\hat{\beta})_{(k+1)(k+1)}}
\]

This results in

\begin{longtable}[c]{@{}lllll@{}}
\toprule
& \(\hat{\beta_k}\) & \(\hat{\sigma}_k\) & t & p\tabularnewline
\midrule
\endhead
\(\beta_0\) & -1.16 & 1.97 & -0.59 & 0.709\tabularnewline
\(\beta_1\) & 0.14 & 0.45 & 0.30 & 0.389\tabularnewline
\(\beta_2\) & 0.02 & 0.24 & 0.08 & 0.468\tabularnewline
\(\beta_3\) & 0.12 & 0.01 & 9.97 & 0.0009\tabularnewline
\bottomrule
\end{longtable}

\subsection{\texorpdfstring{c)
\(H_0: \beta_0 = 0, \beta_1 = \beta_3, \beta_2 = 0; \mathbf{C} \boldsymbol{\beta} = \mathbf{t}\)}{c) H\_0: \textbackslash{}beta\_0 = 0, \textbackslash{}beta\_1 = \textbackslash{}beta\_3, \textbackslash{}beta\_2 = 0; \textbackslash{}mathbf\{C\} \textbackslash{}boldsymbol\{\textbackslash{}beta\} = \textbackslash{}mathbf\{t\}}}\label{c-hux5f0-betaux5f0-0-betaux5f1-betaux5f3-betaux5f2-0-mathbfc-boldsymbolbeta-mathbft}

In matrix notation: \[
\begin{pmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & -1\\
0 & 0 & 1 & 0\\
\end{pmatrix}\\
\begin{pmatrix}
\beta_0\\
\beta_1\\
\beta_2\\
\beta_3\\
\end{pmatrix}\\
=
\begin{pmatrix}
0\\
0\\
0\\
\end{pmatrix}\\
\]

\subsection{d)}\label{d}

reduced model
\[ y_i = (\underbrace{x_{i1} + x_{i3}}_{\tilde{x_i}} \boldsymbol{\beta}+\boldsymbol{\varepsilon_i}) \]

\[
\begin{aligned}
\tilde{x_i} &= 
\begin{pmatrix}
x_{11} + x_{13}\\
\dots \\
x_{11} + x_{13}\\
\end{pmatrix}
=
\mathbf{x}_1 + \mathbf{x}_3\\[20pt]
\hat{\beta} &= (\tilde{x_1}' \tilde{x})^{-1} \tilde{x_1} y\\[20pt]
x &=
\begin{pmatrix}
1      & x_{11} & \dots  & x_{13} \\
\vdots & \vdots & \ddots & \vdots \\
1      & x_{n1} & \dots  & x_{n3}\\
\end{pmatrix}\\[20pt]
x'x &= 
\begin{pmatrix}
n                 & \sum_{}^{} x_{i1}            & \sum_{}^{} x_{i2}        & \sum_{}^{} x_{i3} \\
\sum_{}^{} x_{i1} & \mathbf{\sum_{}^{} x_{i1}^2} & \sum_{}^{} x_{i1} x_{i2} & \sum_{}^{} x_{i1} x_{i3} \\
\sum_{}^{} x_{i2} & \dots                        & \sum_{}^{} x_{i2}^2      & \mathbf{\sum_{}^{} x_{i2} x_{i3}} \\
\dots             & \dots                        & \dots                    & \mathbf{\sum_{}^{} x_{i3}^2} \\
\end{pmatrix}\\[20pt]
\tilde{x}'\tilde{x} &= (x_1 + x_3)'(x_1+x_3) \\
&= x_1 x_1 + 2 x_1 x_3 + x_3 x_3 \\
&= 2114 + 2 * 3583 + 12276 = \underline{21556} \\[20pt]
\tilde{x}'y &= (x_1+x_3)'y \\
&= x_1 y + x_3 y  \\
&= 648 + 1821 = \underline{2469} \\[20pt]
\hat{\beta} &= \frac{2469}{21556} = \underline{\underline{0.11454}} \\[20pt]
\end{aligned}
\] Reduced model: \(\hat{y_i} = 0.114*(x_{i1}+x_{i3})\)

\end{document}
